// Categorias que a Pluggy manda (em inglês), em português, para mostrar ao lado do lançamento
// ("o banco diz: Táxi e transporte por app"). A escolha da categoria em si é feita no banco
// (fin_aplicar_regras); aqui é só a tradução.

const NOMES = {
  income: 'Renda',
  salary: 'Salário',
  retirement: 'Aposentadoria',
  'entrepreneurial activities': 'Atividade empresarial',
  'government aid': 'Auxílio do governo',
  'non recurring income': 'Renda eventual',
  'loans and financing': 'Empréstimos e financiamentos',
  'late payment and overdraft costs': 'Juros de atraso e cheque especial',
  'interests charged': 'Juros cobrados',
  financing: 'Financiamento',
  'real estate financing': 'Financiamento imobiliário',
  'vehicle financing': 'Financiamento de veículo',
  'student loan': 'Crédito estudantil',
  investments: 'Investimentos',
  'automatic investment': 'Investimento automático',
  'fixed income': 'Renda fixa',
  'mutual funds': 'Fundos de investimento',
  'variable income': 'Renda variável',
  margin: 'Margem',
  'proceeds interests and dividends': 'Rendimentos, juros e dividendos',
  pension: 'Previdência',
  'same person transfer': 'Transferência entre suas contas',
  'same person transfer cash': 'Transferência entre suas contas (dinheiro)',
  'same person transfer pix': 'Pix entre suas contas',
  'same person transfer ted': 'TED entre suas contas',
  transfers: 'Transferências',
  'transfer bank slip': 'Boleto',
  'transfer cash': 'Transferência em dinheiro',
  'transfer check': 'Cheque',
  'transfer doc': 'DOC',
  'transfer foreign exchange': 'Câmbio',
  'transfer internal': 'Transferência interna',
  'transfer pix': 'Pix',
  'transfer ted': 'TED',
  'third party transfers': 'Transferência para terceiros',
  'third party transfer pix': 'Pix para terceiros',
  'third party transfer ted': 'TED para terceiros',
  'credit card payment': 'Pagamento de fatura',
  'legal obligations': 'Obrigações legais',
  'blocked balances': 'Saldo bloqueado',
  alimony: 'Pensão alimentícia',
  services: 'Serviços',
  telecommunications: 'Telefone e internet',
  internet: 'Internet',
  mobile: 'Celular',
  tv: 'TV',
  education: 'Educação',
  'online courses': 'Cursos online',
  university: 'Faculdade',
  school: 'Escola',
  kindergarten: 'Creche',
  'wellness and fitness': 'Bem-estar e academia',
  'gyms and fitness centers': 'Academia',
  'sports practice': 'Esportes',
  wellness: 'Bem-estar',
  tickets: 'Ingressos',
  'stadiums and arenas': 'Estádios e arenas',
  'landmarks and museums': 'Passeios e museus',
  'cinema theater and concerts': 'Cinema, teatro e shows',
  shopping: 'Compras',
  'online shopping': 'Compras online',
  electronics: 'Eletrônicos',
  'pet supplies and vet': 'Pet e veterinário',
  clothing: 'Roupas',
  'kids and toys': 'Crianças e brinquedos',
  bookstore: 'Livraria',
  'sports goods': 'Artigos esportivos',
  'office supplies': 'Papelaria',
  cashback: 'Cashback',
  'digital services': 'Serviços digitais',
  gaming: 'Jogos',
  'video streaming': 'Streaming de vídeo',
  'music streaming': 'Streaming de música',
  groceries: 'Mercado',
  'food and drinks': 'Comida e bebida',
  'eating out': 'Restaurantes',
  'food delivery': 'Delivery',
  travel: 'Viagem',
  'airport and airlines': 'Aeroporto e companhias aéreas',
  accommodation: 'Hospedagem',
  'mileage programs': 'Programas de milhas',
  'bus tickets': 'Passagens de ônibus',
  donations: 'Doações',
  gambling: 'Apostas',
  lottery: 'Loteria',
  'online bet': 'Apostas online',
  taxes: 'Impostos',
  'income taxes': 'Imposto de renda',
  'taxes on investments': 'Impostos sobre investimentos',
  'tax on financial operations': 'IOF',
  'bank fees': 'Tarifas bancárias',
  'account fees': 'Tarifa da conta',
  'wire transfer fees and atm fees': 'Tarifas de transferência e saque',
  'credit card fees': 'Tarifas do cartão',
  housing: 'Moradia',
  rent: 'Aluguel',
  utilities: 'Contas da casa',
  water: 'Água',
  electricity: 'Luz',
  gas: 'Gás',
  houseware: 'Casa e decoração',
  'urban land and building tax': 'IPTU',
  healthcare: 'Saúde',
  dentist: 'Dentista',
  pharmacy: 'Farmácia',
  optometry: 'Ótica',
  'hospital clinics and labs': 'Hospitais, clínicas e exames',
  transportation: 'Transporte',
  'taxi and ride hailing': 'Táxi e transporte por app',
  'public transportation': 'Transporte público',
  'car rental': 'Aluguel de carro',
  bicycle: 'Bicicleta',
  automotive: 'Veículo',
  'gas stations': 'Posto de combustível',
  parking: 'Estacionamento',
  'tolls and in vehicle payment': 'Pedágio',
  'vehicle ownership taxes and fees': 'IPVA e taxas do veículo',
  'vehicle maintenance': 'Manutenção do veículo',
  'traffic tickets': 'Multas',
  insurance: 'Seguros',
  'life insurance': 'Seguro de vida',
  'home insurance': 'Seguro residencial',
  'health insurance': 'Plano de saúde',
  'vehicle insurance': 'Seguro do veículo',
  leisure: 'Lazer',
  other: 'Outros',
}

const chave = (texto) =>
  texto
    .toLowerCase()
    .replace(/[^a-z]+/g, ' ')
    .trim()

// "Taxi and ride-hailing" → "Táxi e transporte por app". Sem tradução conhecida, devolve o original.
export function traduzirCategoriaBanco(texto) {
  if (!texto) return null
  return NOMES[chave(texto)] ?? texto
}
